# ==============================================================================
# SilverQuant 完整容器编排配置
# ==============================================================================
#
# 默认使用 Podman (推荐):
#   podman-compose -f docker-compose-full.yml up -d
#   podman-compose -f docker-compose-full.yml down
#
# 也兼容 Docker:
#   docker-compose -f docker-compose-full.yml up -d
#   docker-compose -f docker-compose-full.yml down
#
# 包含服务: Redis 7, MySQL 8.0, ClickHouse
# ==============================================================================

version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: silverquant-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --appendfsync everysec
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  mysql:
    image: mysql:8.0
    container_name: silverquant-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: silverquant2024
      MYSQL_DATABASE: silverquant
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-psilverquant2024"]
      interval: 10s
      timeout: 3s
      retries: 3

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: silverquant-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native TCP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    environment:
      CLICKHOUSE_DB: silverquant
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: silverquant2024
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  redis_data:
    driver: local
  mysql_data:
    driver: local
  clickhouse_data:
    driver: local
  clickhouse_logs:
    driver: local

networks:
  default:
    name: silverquant-network
    driver: bridge
